baseurl: https://blog.nightspace.dynv6.net/
languageCode: zh-cn
theme: hugo-theme-stack
paginate: 5
title: Night Space

languages:
    zh-cn:
        languageName: 中文
        title: Night Space
        description: 一个不务正业的OIer
        weight: 1

# Change it to your Disqus shortname before using
disqusShortname:

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage: zh-cn

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: true

# permalinks:
#     post: /p/:slug/
#     page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2021
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji:
        subtitle: 为不折腾而折腾，才是折腾的最高境界
        avatar:
            enabled: true
            local: false
            src: https://avatars.githubusercontent.com/u/63776734

    article:
        math: true
        toc: true
        readingTime: true
        license:
            enabled: true
            default: "[署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/)"

    comments:
        enabled: true
        provider: giscus

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/component.html
        waline:
            serverURL:
            lang:
            pageview:
            emoji:
                - https://unpkg.com/@waline/emojis@1.0.1/weibo
            requiredMeta:
                - name
                - email
                - url
            locale:
                admin: Admin
                placeholder:

        twikoo:
            envId:
            region:
            path:
            lang:

        # See https://cactus.chat/docs/reference/web-client/#configuration for description of the various options
        cactus:
            defaultHomeserverUrl: "https://matrix.cactus.chat:8448"
            serverName: "cactus.chat"
            siteName: "" # You must insert a unique identifier here matching the one you registered (See https://cactus.chat/docs/getting-started/quick-start/#register-your-site)

        giscus:
            repo: NightSpaceC/blog
            repoID: R_kgDOH7TGUA
            category: giscus
            categoryID: DIC_kwDOH7TGUM4CRMRD
            mapping: pathname
            lightTheme: light
            darkTheme: dark
            reactionsEnabled: 1
            emitMetadata: 0
            lang: zh-CN

        gitalk:
            owner:
            admin:
            repo:
            clientID:
            clientSecret:

        cusdis:
            host:
            id:
    
    analytics:
        enabled: true
        provider: cloudflare
        cloudflare:
            token: 58e4125f7abc491fa8a29447400d8df1

    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

    yuruChara:
        enabled: true
        live2d_widget: https://gcore.jsdelivr.net/gh/NightSpaceC/live2d-widget@master/autoload.js

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: 首页
          url: /
          weight: 10
          params:
              icon: home
        - identifier: search
          name: 搜索
          url: /page/search/
          weight: 20
          params:
              icon: search
        - identifier: archives
          name: 归档
          url: /page/archives/
          weight: 30
          params:
              icon: archives
        - identifier: tools
          name: 工具箱
          url: /page/tools/
          weight: 40
          params:
              icon: tools
        - identifier: about
          name: 关于
          url: /page/about/
          weight: 50
          params:
              icon: user

    social:
        - identifier: email
          name: EMail
          url: mailto:NightSpaceC@outlook.com
          params:
              icon: mail

        - identifier: github
          name: GitHub
          url: https://github.com/NightSpaceC
          params:
              icon: brand-github

        - identifier: rss
          name: RSS
          url: https://blog.nightspace.dynv6.net/index.xml
          params:
              icon: rss

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: true
    tableOfContents:
        endLevel: 6
        ordered: true
        startLevel: 1
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
